"""Unit and Integration Tests for PQC Expansion Phase (WS-EXP.1, WS-EXP.2, WS-EXP.3).

Verifies:
1. PyTorch 1D-CNN and MLP architectures, tensor shapes, and forward passes.
2. Checkpoint availability and training metric validation.
3. FastAPI REST endpoints: health, security estimation, quantum resources, CBOM, model prediction.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

import torch
from fastapi.testclient import TestClient

from pqc_bench.api.main import app
from pqc_bench.models.side_channel_cnn import LWEDistinguisherMLP, SideChannel1DCNN


class TestModelArchitectures(unittest.TestCase):
    """Verifies PyTorch model construction and tensor dimensions."""

    def test_side_channel_1d_cnn_shapes(self) -> None:
        """Verifies 1D-CNN accepts (batch, 256) and outputs (batch, 9) logits."""
        model = SideChannel1DCNN(input_length=256, num_classes=9)
        model.eval()

        batch_size = 8
        dummy_input = torch.randn(batch_size, 256)
        with torch.no_grad():
            logits = model(dummy_input)
            probs = model.predict_probabilities(dummy_input)

        self.assertEqual(logits.shape, (batch_size, 9))
        self.assertEqual(probs.shape, (batch_size, 9))
        # Probabilities must sum to 1.0
        sums = probs.sum(dim=-1).numpy()
        for s in sums:
            self.assertAlmostEqual(float(s), 1.0, places=4)

    def test_lwe_distinguisher_mlp_shapes(self) -> None:
        """Verifies LWE MLP accepts (batch, 8) and outputs (batch, 2) distinguishing logits."""
        model = LWEDistinguisherMLP(input_dim=8, hidden_dims=(32, 64, 32), num_classes=2)
        model.eval()

        batch_size = 16
        dummy_input = torch.randn(batch_size, 8)
        with torch.no_grad():
            logits = model(dummy_input)
            scores = model.distinguish_score(dummy_input)

        self.assertEqual(logits.shape, (batch_size, 2))
        self.assertEqual(scores.shape, (batch_size,))
        self.assertTrue(torch.all(scores >= 0.0) and torch.all(scores <= 1.0))


class TestTrainingArtifacts(unittest.TestCase):
    """Verifies checkpoints and metrics generated by WS-EXP.1."""

    def setUp(self) -> None:
        self.repo_root = Path(__file__).resolve().parent.parent
        self.artifacts_dir = self.repo_root / "artifacts"
        self.checkpoints_dir = self.artifacts_dir / "checkpoints"
        self.metrics_dir = self.artifacts_dir / "metrics"

    def test_checkpoint_files_exist(self) -> None:
        cnn_ckpt = self.checkpoints_dir / "side_channel_cnn.pt"
        lwe_ckpt = self.checkpoints_dir / "lwe_mlp.pt"
        self.assertTrue(cnn_ckpt.exists(), f"Missing checkpoint: {cnn_ckpt}")
        self.assertTrue(lwe_ckpt.exists(), f"Missing checkpoint: {lwe_ckpt}")

    def test_training_metrics_validity(self) -> None:
        metrics_file = self.metrics_dir / "training_results.json"
        self.assertTrue(metrics_file.exists(), f"Missing metrics: {metrics_file}")

        with open(metrics_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        self.assertEqual(data["status"], "SUCCESS")
        self.assertIn("side_channel_cnn", data)
        self.assertIn("lwe_distinguisher_mlp", data)

        cnn_data = data["side_channel_cnn"]
        self.assertGreater(cnn_data["epochs_trained"], 0)
        self.assertGreater(cnn_data["best_val_accuracy"], 0.20)
        self.assertEqual(cnn_data["final_guessing_entropy"], 1.0)


class TestFastAPIRoutes(unittest.TestCase):
    """Integration test suite for the FastAPI service endpoints."""

    def setUp(self) -> None:
        self.client = TestClient(app)

    def test_health_endpoint(self) -> None:
        resp = self.client.get("/health")
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertEqual(body["status"], "healthy")
        self.assertEqual(body["compute_device"], "cpu")
        self.assertTrue(body["checkpoints_available"]["side_channel_cnn"])

    def test_dashboard_html_endpoint(self) -> None:
        resp = self.client.get("/")
        self.assertEqual(resp.status_code, 200)
        self.assertIn("NIST Post-Quantum Cryptography & ML Engine", resp.text)
        self.assertIn("tab-overview", resp.text)

    def test_security_estimate_endpoint(self) -> None:
        resp = self.client.post("/api/v1/security-estimate", json={"scheme": "ml-kem-768"})
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertEqual(body["estimated_security_bits"], 192)
        self.assertEqual(body["nist_category"], "cat3")

    def test_quantum_cost_endpoint(self) -> None:
        resp = self.client.post("/api/v1/quantum-cost", json={"scheme": "ml-kem-768"})
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertIn("comparison", body)
        self.assertGreater(body["comparison"]["aqre_logical_qubits"], 1000)

    def test_model_predict_endpoint(self) -> None:
        resp = self.client.post("/api/v1/model/predict", json={"target_operation": "ML-KEM-768 NTT"})
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertIn("predicted_hamming_weight", body)
        self.assertIn("confidence", body)
        self.assertEqual(len(body["hamming_weight_probabilities"]), 9)
        self.assertIn(body["vulnerability_level"], ["HIGH", "MEDIUM", "LOW / CONSTANT_TIME"])

    def test_project_status_endpoint(self) -> None:
        resp = self.client.get("/api/v1/status")
        self.assertEqual(resp.status_code, 200)
        body = resp.json()
        self.assertEqual(body["project"], "Post-Quantum-Cryptography-ML")
        self.assertEqual(len(body["workstreams"]), 11)


if __name__ == "__main__":
    unittest.main()
